const Data = [
      {
        id: 1,
        time: "1day ago",
        cover: "https://i.ibb.co/1bBTS7w/istockphoto-1309328823-612x612.jpg",
        name: "James",
        rating: 4.0,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
      },
      {
        id: 2,
        time: "10hr ago",
        cover: "https://i.ibb.co/CWDyN6w/istockphoto-637914452-612x612.jpg",
        name: "William",
        rating: 5.0,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
      },
      {
        id: 3,
        time: "5day ago",
        cover: "https://i.ibb.co/9YK15GS/images.jpg",
        name: "Jessica",
        rating: 4.5,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
      },
      {
        id: 4,
        time: "a week ago",
        cover: "https://i.ibb.co/Z2KYDNb/images-2.jpg",
        name: "Thomas",
        rating: 4.00,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
      },
      {
        id: 5,
        time: "1day ago",
        cover: "https://i.ibb.co/gd6DB2D/download.jpg",
        name: "Richard",
        rating: 3.5,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
      },
      {
        id: 6,
        time: "4day ago",
        cover: "https://i.ibb.co/MSsGDP0/images-1.jpg",
        name: "Mary",
        rating: 3.0,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
      },
    ]
  export default Data